### ISSUE TITLE
`jax[tpu]` should degrade gracefully when run on a machine without a TPU

### ISSUE THREAD

**Issue by hawkinsp** [google/jax#11668]
See https://github.com/google/jax/discussions/11604

It appears we print many scary and confusing log messages when this happens. If there's no TPU present on the machine (e.g., the device nodes aren't present) we should fail politely.

From the discussion thread:

```
>>> from jax import grad
/home/swang/venv/moffett_20220721tpu2/lib/python3.8/site-packages/jax/__init__.py:27: UserWarning: cloud_tpu_init failed: KeyError('')
 This a JAX bug; please report an issue at https://github.com/google/jax/issues
  _warn(f"cloud_tpu_init failed: {repr(exc)}\n This a JAX bug; please report "
>>> import jax.numpy as jnp
>>> 
>>> def tanh(x):  # Define a function
...   y = jnp.exp(-2.0 * x)
...   return (1.0 - y) / (1.0 + y)
... 
>>> grad_tanh = grad(tanh)  # Obtain its gradient function
```
Calling devices() for the first time has errors, but not subsequent ones

```
>>> jax.devices()
WARNING: Logging before InitGoogle() is written to STDERR
I0000 00:00:1658969750.942706    7367 common_lib.cc:144] Failed to fetch URL on try 1 out of 6: Couldn't connect to server
I0000 00:00:1658969754.014705    7367 common_lib.cc:144] Failed to fetch URL on try 2 out of 6: Couldn't connect to server
I0000 00:00:1658969757.086732    7367 common_lib.cc:144] Failed to fetch URL on try 3 out of 6: Couldn't connect to server
I0000 00:00:1658969760.158768    7367 common_lib.cc:144] Failed to fetch URL on try 4 out of 6: Couldn't connect to server
^C^CI0000 00:00:1658969763.230709    7367 common_lib.cc:144] Failed to fetch URL on try 5 out of 6: Couldn't connect to server
I0000 00:00:1658969766.302714    7367 common_lib.cc:144] Failed to fetch URL on try 6 out of 6: Couldn't connect to server
Failed to get accelerator type with error: Couldn't connect to serverI0000 00:00:1658969769.374712    7367 common_lib.cc:144] Failed to fetch URL on try 1 out of 6: Couldn't connect to server
I0000 00:00:1658969772.446723    7367 common_lib.cc:144] Failed to fetch URL on try 2 out of 6: Couldn't connect to server


>>> jax.devices()
[CpuDevice(id=0)]
>>> jax.devices("tpu")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/swang/venv/moffett_20220721tpu2/lib/python3.8/site-packages/jax/_src/lib/xla_bridge.py", line 449, in devices
    return get_backend(backend).devices()
  File "/home/swang/venv/moffett_20220721tpu2/lib/python3.8/site-packages/jax/_src/lib/xla_bridge.py", line 391, in get_backend
    return _get_backend_uncached(platform)
  File "/home/swang/venv/moffett_20220721tpu2/lib/python3.8/site-packages/jax/_src/lib/xla_bridge.py", line 383, in _get_backend_uncached
    raise RuntimeError(f"Unknown backend {platform}")
RuntimeError: Unknown backend tpu
>>> jax.devices("cpu")
[CpuDevice(id=0)]
```

**Comment by selamw1** [comment]
Hi @hawkinsp 
It appears the issue has been resolved. I executed the mentioned code using JAX version 0.4.13 on a virtual machine without a TPU, and it functioned correctly.

```Python
>>> from jax import grad
>>> import jax.numpy as jnp
>>> import jax
>>> 
>>> def tanh(x):
...     y = jnp.exp(-2.0 * x)
...     return (1.0 - y) / (1.0 + y)
... 
>>> grad_tanh = grad(tanh) # Obtain its gradient function
>>> 
```
Calling devices() for the first time:
```Python
>>> jax.devices() 
[gpu(id=0), gpu(id=1)]
>>>  
>>> jax.devices("cpu") 
[CpuDevice(id=0)]
>>> 
>>> jax.devices("gpu") 
[gpu(id=0), gpu(id=1)]
>>> 
>>> jax.devices("tpu") 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/selamw/.local/lib/python3.8/site-packages/jax/_src/xla_bridge.py", line 758, in devices
    return get_backend(backend).devices()
  File "/home/selamw/.local/lib/python3.8/site-packages/jax/_src/xla_bridge.py", line 692, in get_backend
    return _get_backend_uncached(platform)
  File "/home/selamw/.local/lib/python3.8/site-packages/jax/_src/xla_bridge.py", line 679, in _get_backend_uncached
    raise RuntimeError(f"Backend '{platform}' failed to initialize: "
RuntimeError: Backend 'tpu' failed to initialize: module 'jaxlib.xla_extension' has no attribute 'get_tpu_client'
```

**Comment by jakevdp** [comment]
Hi @selamw1 – in order to reprodue this error, you'd have to install the `jax[tpu]` dependencies on a non-TPU machine:
```
pip install jax[tpu] -f https://storage.googleapis.com/jax-releases/libtpu_releases.html
```
When I do this and run `jax.devices()`, it hangs for nearly a minute before spitting out this:
```
XlaRuntimeError: UNKNOWN: TPU initialization failed: No ba16c7433 device found.

During handling of the above exception, another exception occurred:

RuntimeError                              Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/jax/_src/xla_bridge.py](https://localhost:8080/#) in backends()
    664           else:
    665             err_msg += " (you may need to uninstall the failing plugin package, or set JAX_PLATFORMS=cpu to skip this backend.)"
--> 666           raise RuntimeError(err_msg)
    667 
    668     assert _default_backend is not None

RuntimeError: Unable to initialize backend 'tpu': UNKNOWN: TPU initialization failed: No ba16c7433 device found. (set JAX_PLATFORMS='' to automatically choose an available backend)
```
So perhaps a better error than before, but I think the original issue still stands.

**Comment by rivershah** [comment]
This hands on a vm without `tpu`

```
import jax
import keras

print("jax version:", jax.__version__)
print("keras version:", keras.__version__)


from keras import ops

x = ops.ones((1, 2, 3))

```

```
jax version: 0.6.0
keras version: 3.9.2
Failed to get TPU metadata (tpu-env) from instance metadata for variable CHIPS_PER_HOST_BOUNDS: INTERNAL: Failed to fetch URL after 30 tries (http status: 404); curl status: No error
=== Source Location Trace: ===
learning/45eac/tfrc/runtime/gcp_metadata_utils.cc:93
learning/45eac/tfrc/runtime/env_var_utils.cc:50
```

**Comment by skye** [comment]
Try setting `TPU_SKIP_MDS_QUERY=1`. That should get rid of the `Failed to fetch URL on try 1 out of 6: Couldn't connect to server` messages + slowness. We should definitely make this smoother, but that's a workaround for now.
