### ISSUE TITLE
Apple Silicon: error: failed to legalize operation 'mhlo.triangular_solve'

### ISSUE THREAD

**Issue by yu-fz** [google/jax#17490]
### Description

Matrix inversion appears to be broken on jax-metal. 
Apologies in advance if this is not the right place to report the issue.

Repro:

```
import jax
import jax.numpy as jnp
jax.config.update('jax_platform_name', 'METAL')

A = jnp.ones((3, 3))
B = jnp.linalg.inv(A)
```

### What jax/jaxlib version are you using?

jax 0.4.11, jaxlib 0.4.10

### Which accelerator(s) are you using?

GPU/Metal

### Additional system info

Mac OS 13.5.1, M1 Max

**Comment by p-i-** [comment]
<crickets>
Would be a +1 for optics if assignees could 👍 to acknowledge receipt of the task.
There's a handful of bugs around core operations with no indication of progress nor what's blocking them.
Guessing it's Apple dragging their heels; do they not have the firepower to provide (uniquely) a software-stack to support their own hardware that's 1+ years old now? Seems cringe that the feeling of UX disappointment should fall unfairly upon JAX.

**Comment by benjaminvatterj** [comment]
Just to add this and a plethora of other fundamental jax operations simply don't work on Jax-metal with no update insight. At this point, jax-metal is quite useless as far as I have been able to test it. As of version Jax-metal 0.0.4, I would say simply avoid it and install Jax on CPU.

**Comment by benjaminvatterj** [comment]
Just FYI, it seems like Apple released a new version of metal-jax a few weeks back: version 0.0.5.
This basic feature is still broken.

**Comment by crondonm** [comment]
Same issue here. Any idea when a fix will be released?

**Comment by nngabe** [comment]
I will ping this and add that I hope this gets fixed in the next release. 

I think the JAX + Apple Silicon combo offers some unique advantages for prototyping models locally (i.e. smaller compute but larger RAM compared to a comparable NVIDIA workstation). I think JAX users will pick up on this pretty quickly once features like this are fixed.

**Comment by shuhand0** [comment]
We are looking into adding the conversion for the op.

**Comment by mvanaltvorst** [comment]
I also hope this gets fixed soon! Do you happen to have any updates @shuhand0? Thanks

**Comment by TheSkyentist** [comment]
As of jax-metal 0.1.1 this issue still persists, at least in my configuration. 

MacOS 15.0.1
Apple M2 Pro

**Comment by yu-fz** [comment]
> As of jax-metal 0.1.1 this issue still persists, at least in my configuration.
> 
> MacOS 15.0.1 Apple M2 Pro

😭 😭 😭  bruh

**Comment by Eureka10shen** [comment]
Same problem on M3 Max with
```
jax                       0.4.34                   pypi_0    pypi
jax-metal                 0.1.1                    pypi_0    pypi
jaxlib                    0.4.34                   pypi_0    pypi
```
😭😭😭

**Comment by reeceomahoney** [comment]
Still experiencing this issue on M1 mac with MacOS 15.5, jax 0.5.0, jaxlib 0.5.0, and jax-metal 0.1.1. Wondering if there has been any update?

**Comment by jakevdp** [comment]
The last release of jax-metal was over a year ago now, and so it seems pretty clear that the team behind it is no longer working on it. We've removed mentions of jax-metal from JAX's installation docs: at this point I think it's probably best for users to consider the jax-metal project dead, and to focus on using supported backends.
