### ISSUE TITLE
Omnistaging breaks LSTM Model

### ISSUE THREAD

**Issue by n2cholas** [google/jax#4448]
Omnistaging causes the following code to crash:

```python
import time

import numpy as np
import haiku as hk
import jax
import jax.numpy as jnp
from jax import grad, jit, random, vmap

vocab_size = 1000
seq_length = 80
batch_size = 8

def neural_net(x):
    embed_init = hk.initializers.TruncatedNormal(stddev=0.02)
    o2 = hk.Embed(vocab_size + 4, 100, w_init=embed_init)(x)
    o2 = jnp.reshape(o2, (o2.shape[1], o2.shape[0], o2.shape[2]))

    core = hk.LSTM(100)
    outs, state = hk.static_unroll(core, o2, core.initial_state(x.shape[0]))
    outs = outs.reshape(outs.shape[1], outs.shape[0], outs.shape[2])

    red_dim_outs = hk.avg_pool(outs, seq_length, seq_length, "SAME").squeeze()
    return hk.Linear(2)(red_dim_outs)

def loss(params, inputs, targets):
    logits = model.apply(params, None, inputs)
    one_hot = jax.nn.one_hot(targets, logits.shape[-1])
    return -jnp.mean(jnp.sum(jax.nn.log_softmax(logits) * one_hot, axis=-1))

x = np.random.randint(0, vocab_size, size=(batch_size, seq_length))
y = np.random.random((batch_size,)).round()

model = hk.transform(neural_net)
rng = jax.random.PRNGKey(42)
params = model.init(rng, np.random.randint(1, size=x.shape))

start_time = time.time()
jit(grad(loss))(params, x, y)
end_time = time.time()
print(end_time - start_time)
```

Running this with `JAX_OMNISTAGING=0 python main.py` works and is pretty quick (~20 seconds), but using `JAX_OMNISTAGING=1 python main.py` causes the program to be killed by the kernel.

Below is the output of `pip freeze`:
```
absl-py==0.10.0
dm-haiku==0.0.2
jax==0.2.0
jaxlib @ https://storage.googleapis.com/jax-releases/cuda110/jaxlib-0.1.55-cp38-none-manylinux2010_x86_64.whl
numpy==1.19.2
opt-einsum==3.3.0
scipy==1.5.2
six==1.15.0
```

I'm not sure if this is a Haiku or JAX issue, so please let me know if I should open this issue in the Haiku repo instead. Thanks in advance!

**Comment by mattjj** [comment]
@tomhennigan @LenaMartens any thoughts?

**Comment by mattjj** [comment]
@n2cholas by the way, check out [this omnistaging doc](https://github.com/google/jax/blob/master/design_notes/omnistaging.md) if you haven't already.

From your description, it sounds plausible this might be triggering an XLA bug, which may be backend-specific. Is this on CPU or GPU?

**Comment by n2cholas** [comment]
@mattjj Thanks for the link! Based on that doc, my code seems fine since there are no shape computations nor side effects in the JIT'd code.

This is on the GPU: Ubuntu 18.04, CUDA 11.0.228, NVIDIA-SMI 450.66, Titan V GPU.

**Comment by tomhennigan** [comment]
Hey @n2cholas , I think this is fixed at head in Haiku. Your snippet works for me in Google Colab when I install from git:

```shell
$ pip install git+https://github.com/deepmind/dm-haiku
```

We will make a new minor release of Haiku soon (next week I think) with all of these changes in.

(BTW I would suggest using `dynamic_unroll` not `static_unroll` since this should make your code compile faster for long sequences, and `jit`-ing your init function may actually speed things up too.)

**Comment by n2cholas** [comment]
Thanks @tomhennigan. I upgraded haiku to heda just now, and the code still did not run for me with omnistaging. However, switching the `static_unroll` to a `dynamic_unroll` fixed it. 

In general, when should you use `static_unroll` vs `dynamic_unroll`? Here, I chose to use static because the sequence length is pretty short (80) and all the sequences have the same length.

**Comment by pranavsubramani** [comment]
To add to @n2cholas, technically sequences can be padded to ensure that they have the same sequence length. Is there a rule of thumb for when we should expect better performance with `static_unroll`?

**Comment by mattjj** [comment]
It seems this is still an issue! I think this is showing us an XLA compile time bug, which we should try to fix or else work around if we can. (See also [this comment I just left on deepmind/dm-haiku#77](https://github.com/deepmind/dm-haiku/issues/77#issuecomment-712517647).)

The next step is for some Googler / DMer to open a bug against XLA:GPU to see if they have any ideas about improving the compile time.

**Comment by mattjj** [comment]
[Here's the gist](https://colab.sandbox.google.com/gist/n2cholas/67fdc71bbae404b37a9f118c2a59d81d/haiku-lstm.ipynb) that shows the issue, at github HEAD for both JAX and Haiku, with omnistaging enabled.

**Comment by n2cholas** [comment]
This is no longer an issue with the latest JAX and Haiku on PyPI. [Here's a gist](https://colab.research.google.com/gist/n2cholas/24d64e33a5fb148471a93dd21b65ce7f/scratchpad.ipynb) that runs on Colab. Thanks for the fix!
