### ISSUE TITLE
jit changes behaviour of sparse.coo_matmat with transposed argument

### ISSUE THREAD

**Issue by dimasad** [google/jax#7533]
JIT gives erroneous results for the multiplication of a sparse matrix with a transposed dense matrix.

```python

import jax
import jax.numpy as jnp
import jax.experimental.sparse as jsparse

d = jnp.r_[0.1, 2., 3., -2]
x = jax.random.normal(jax.random.PRNGKey(0), (3, 3))


def ok(d, x):
    i = jnp.r_[0, 0, 1, 2]
    j = jnp.r_[0, 2, 0, 0]
    shape = (3, 3)
    return jsparse.coo_matmat(d, i, j, x, shape=shape)


def NOT_ok(d, x):
    i = jnp.r_[0, 0, 1, 2]
    j = jnp.r_[0, 2, 0, 0]
    shape = (3, 3)
    return jsparse.coo_matmat(d, i, j, x.T, shape=shape)

e_ok = ok(d, x) - jax.jit(ok)(d, x)
e_not_ok = NOT_ok(d, x) - jax.jit(NOT_ok)(d, x)

print('ok: error = \n', e_ok)
print('\nNOT ok: error = \n',e_not_ok)
## OUTPUT
#ok: error = 
# [[0. 0. 0.]
# [0. 0. 0.]
# [0. 0. 0.]]
#
#NOT ok: error = 
# [[ 0.97765154  0.7773348  -0.0488826 ]
# [ 0.         -3.0031524  -1.4664774 ]
# [ 0.          2.0021017   0.9776516 ]]
```

**Comment by jakevdp** [comment]
Are you seeing this only on a GPU backend?

**Comment by jakevdp** [comment]
I don't reproduce the issue on CPU; I suspect it has to do with the lowering to cusparse. We need to change the layout definition here for a transposed matrix: https://github.com/google/jax/blob/c94f41290cc5c28fba059e172279994107c3103e/jaxlib/cusparse.py#L285

But I'm not certain how to tell at this level whether the input buffer is transposed... perhaps XLA operators somehow expose their strides?

**Comment by dimasad** [comment]
Yes, I'm seeing this on a GPU backend only.

**Comment by jakevdp** [comment]
I took a closer look at this and realized that in the transposed version, you're computing the matrix product of a (3,3) matrix and a (4, 3) matrix, which should be an error! The issue is poor input validation, which should be fixed by #7557.

The reason that there are different answers between GPU/JIT and non-jit approaches is that the two proceed based on different sets assumptions about the input, both of which are incorrect in their own way. With #7557, this should correctly result in an assertion error in both cases.

**Comment by dimasad** [comment]
> I took a closer look at this and realized that in the transposed version, you're computing the matrix product of a (3,3) matrix and a (4, 3) matrix, which should be an error! The issue is poor input validation, which should be fixed by #7557.

Sorry, I think I was distracted while making this minimum working example, in my application where this bug first surfaced the dimensions matched and the JIT messed up the results. I've changed the dimension of the `x` matrix in the example to a square matrix and the error persists.

> The reason that there are different answers between GPU/JIT and non-jit approaches is that the two proceed based on different sets assumptions about the input, both of which are incorrect in their own way. With #7557, this should correctly result in an assertion error in both cases.

In the up side, I guess this helped improve the package in other ways with the validation.

**Comment by jakevdp** [comment]
Great, thanks for checking! I'll try to get to the bottom of the new & improved repro.

**Comment by jakevdp** [comment]
I think I found the issue – should be fixed by #7560
